name: CI-CD
on:
  push:
    branches: [ "dev" ]

jobs:
  build-test-scan-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: amoldevakate2026/azodha.run.place
      IMAGE_TAG: ${{ github.sha }}

    steps:
    # -------------------------
    # 1. Checkout Source Code
    # -------------------------
    - name: Checkout code
      uses: actions/checkout@v4

    # -------------------------
    # 2. Run Unit Tests
    # -------------------------
    - name: Run tests
      run: |
        pip install -r app/requirements.txt
        pytest app/

    # -------------------------
    # 3. SonarQube Scan
    # -------------------------
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    # -------------------------
    # 4. Docker Login (DockerHub)
    # -------------------------
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # -------------------------
    # 5. Build Docker Image
    # -------------------------
    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest

    # -------------------------
    # 6. Trivy Image Scan
    # -------------------------
    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: $IMAGE_NAME:$IMAGE_TAG
        format: table
        exit-code: 1
        severity: CRITICAL,HIGH

    # -------------------------
    # 7. Push Image to DockerHub
    # -------------------------
    - name: Push Docker image
      run: |
        docker push $IMAGE_NAME:$IMAGE_TAG
        docker push $IMAGE_NAME:latest

    # -------------------------
    # 8. Configure AWS Credentials
    # -------------------------
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # -------------------------
    # 9. Deploy to EKS
    # -------------------------
    - name: Deploy to EKS
      run: |
        aws eks update-kubeconfig --name EKS_CLOUD --region us-east-1
        kubectl set image deployment/azodha-project \
          azodha-project=$IMAGE_NAME:$IMAGE_TAG
        kubectl rollout status deployment/azodha-project
